FROM --platform=linux/amd64 node:18-alpine
RUN apk add g++ make py3-pip
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}
WORKDIR /home/node/app
COPY ./ .
RUN npm install
RUN npx prisma generate
# RUN npx prisma migrate deploy
RUN npm run build
RUN chown -R node:node /home/node/app
EXPOSE 3001
CMD ["npm", "run", "start"]