-- CreateTable
CREATE TABLE `DepartmentOfEnergyDataItem` (
    `id` VARCHAR(191) NOT NULL,
    `identifier` VARCHAR(191) NULL,
    `accessLevel` VARCHAR(191) NULL,
    `contactPoint` JSON NULL,
    `programCode` JSON NULL,
    `description` LONGTEXT NULL,
    `title` VARCHAR(500) NULL,
    `distribution` JSON NULL,
    `license` VARCHAR(191) NULL,
    `bureauCode` JSON NULL,
    `modified` JSON NULL,
    `publisher` JSON NULL,
    `accrualPeriodicity` VARCHAR(191) NULL,
    `keyword` JSON NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,
    `org` VARCHAR(191) NULL,
    `vcard` VARCHAR(191) NULL,
    `foaf` VARCHAR(191) NULL,
    `dc` VARCHAR(191) NULL,
    `pod` VARCHAR(191) NULL,
    `skos` VARCHAR(191) NULL,
    `describedBy` JSON NULL,
    `downloadURL` JSON NULL,
    `accessURL` JSON NULL,
    `issued` JSON NULL,
    `language` JSON NULL,
    `rights` VARCHAR(191) NULL,
    `spatial` LONGTEXT NULL,
    `conformsTo` JSON NULL,
    `temporal` VARCHAR(191) NULL,
    `format` VARCHAR(191) NULL,
    `homepage` VARCHAR(191) NULL,
    `dataQuality` BOOLEAN NULL,
    `describedByType` VARCHAR(191) NULL,
    `primaryITInvestmentUII` VARCHAR(191) NULL,
    `fn` VARCHAR(191) NULL,
    `hasEmail` VARCHAR(191) NULL,
    `name` VARCHAR(191) NULL,
    `subOrganizationOf` VARCHAR(191) NULL,
    `landingPage` VARCHAR(500) NULL,
    `references` JSON NULL,
    `theme` JSON NULL,
    `systemOfRecords` VARCHAR(191) NULL,
    `isPartOf` VARCHAR(191) NULL,

    UNIQUE INDEX `DepartmentOfEnergyDataItem_identifier_key`(`identifier`),
    INDEX `title_index`(`title`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
